name: SonarTest
env: 
  BUILD_CONFIG: ${{ vars.BUILD_CONFIG}}
on:
  workflow_dispatch:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main
jobs:
  sonar-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: echo "Test Sonar"
    - name: Checkout Repository Code
      uses: actions/checkout@v6
    - name: Install .NET 10
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
    - name: Build Project
      run: dotnet build --configuration ${{ env.BUILD_CONFIG }}
    - name: Test Project
      run: dotnet test --configuration ${{ env.BUILD_CONFIG }}
    - name: Run Code
      run: dotnet run --project Y2021D01.Tests/Y2021D01.Tests.csproj
