name: TomteTest
on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main
jobs:
  Tomte-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: echo "Test Tomte"
    - name: checkout repository code
      uses: actions/checkout@v6
      run: echo "${{github.repository}} repository has been cloned"
    - name: install .NET 10
      uses: actions/setup-dotnet@v6
      with: 
        dotnet-version: '10.0.x'
    - name: build projekt
      run: dotnet build
    - name: test projekt
      run: dotnet test
    - name: run code
      run: dotnet run --project Y2021D02.Tests/Y2021D02.Tests.csproj          

  
