name: TomteTest
on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main
jobs:
  Tomte-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: echo "Test Tomte"

  
